name: Deploy cinema service to STG

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to STG
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.dev.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEV_SSH_PORT }} -H ${{ secrets.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy .env.example as .env
        run: cp .env.example .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker compose -f $COMPOSE_FILE --env-file .env build

      - name: Tag image for Docker Hub
        run: |
          image=$(docker compose -f $COMPOSE_FILE config | grep "image:" | awk '{print $2}')
          docker tag $image nextfilms/cinema-app:latest

      - name: Push image to Docker Hub
        run: docker push nextfilms/cinema-app:latest

      - name: Save image as tar
        run: |
          mkdir -p images
          docker save nextfilms/cinema-app:latest -o images/app.tar

      - name: Transfer image, .env and compose file to remote server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEV_SSH_PORT }} ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }} "mkdir -p ${{ secrets.DEV_REMOTE_PATH }}/upload"
          
          rsync -avz -e "ssh -p ${{ secrets.DEV_SSH_PORT }} -o StrictHostKeyChecking=no" images/app.tar ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }}:${{ secrets.DEV_REMOTE_PATH }}/upload/app.tar
          
          rsync -avz -e "ssh -p ${{ secrets.DEV_SSH_PORT }} -o StrictHostKeyChecking=no" .env ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }}:${{ secrets.DEV_REMOTE_PATH }}/.env
          
          rsync -avz -e "ssh -p ${{ secrets.DEV_SSH_PORT }} -o StrictHostKeyChecking=no" docker-compose.dev.yml ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }}:${{ secrets.DEV_REMOTE_PATH }}/docker-compose.dev.yml

      - name: Load image and restart docker compose remotely
        run: |
          ssh -p ${{ secrets.DEV_SSH_PORT }} ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }} << EOF
          cd ${{ secrets.DEV_REMOTE_PATH }}
          docker load -i upload/app.tar
          docker compose -f docker-compose.dev.yml --env-file .env down
          docker compose -f docker-compose.dev.yml --env-file .env up -d --remove-orphans
          rm upload/app.tar
          EOF
