name: Deploy cinema service to STG

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to STG
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.dev.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEV_SSH_PORT }} -H ${{ secrets.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy .env.example as .env
        run: cp .env.example .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker compose -f $COMPOSE_FILE --env-file .env build
          image=$(docker compose -f $COMPOSE_FILE config | grep "image:" | awk '{print $2}')
          docker tag $image nextfilms/cinema-app:latest
          docker push nextfilms/cinema-app:latest

      - name: Deploy on remote server from Docker Hub
        run: |
          ssh -p ${{ secrets.DEV_SSH_PORT }} ${{ secrets.DEV_SSH_USERNAME }}@${{ secrets.DEV_SSH_HOST }} << EOF
          cd ${{ secrets.DEV_REMOTE_PATH }}

          mkdir -p ${{ secrets.DEV_REMOTE_PATH }}

          cp .env.example .env
          cp docker-compose.dev.yml docker-compose.dev.yml

          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

          docker pull nextfilms/cinema-app:latest

          docker compose -f docker-compose.dev.yml --env-file .env down
          docker compose -f docker-compose.dev.yml --env-file .env up -d --remove-orphans
          EOF
